all-nodes:
  master-nodes:
  worker-nodes:

master-nodes:
  hosts:
    - hostname: kube-master-1
      ip-address: 192.168.0.172

worker-nodes:
  hosts:
    - hostname: kube-worker-1
      ip-address: 192.168.0.103
    - hostname: kube-worker-2
      ip-address: 192.168.0.217
    - hostname:  kube-worker-3-nfs
      ip-address: 192.168.0.152
    - hostname: kube-worker-4
      ip-address: 192.168.0.68

configuration:
  username: cian
