name: Release

on:
  push:
    tags:
      - "*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Go Setup
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Run Release
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
          workdir: ./cmd/syncwave
        env:
          GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
